{{- if .Values.canary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "boutique.fullname" . }}-frontend-canary
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "boutique.frontendCanarySelectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.canary.replicaCount }}
  selector:
    matchLabels:
      {{- include "boutique.frontendCanarySelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "boutique.frontendCanarySelectorLabels" . | nindent 8 }}
        version: {{ .Values.canary.image.tag | quote }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.canary.image.repository }}:{{ .Values.canary.image.tag }}"
          imagePullPolicy: {{ .Values.canary.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.frontend.port | quote }}
            - name: APP_VERSION
              value: {{ .Values.canary.image.tag | quote }}
            - name: VARIANT
              value: "canary"
            - name: CANARY_WEIGHT
              value: {{ .Values.canary.weight | quote }}
            - name: PRODUCTCATALOG_URL
              value: "http://{{ include "boutique.fullname" . }}-productcatalog:{{ .Values.productcatalog.port }}"
            - name: CHECKOUT_URL
              value: "http://{{ include "boutique.fullname" . }}-checkout:{{ .Values.checkout.port }}"
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
{{- end }}
