{{- if .Values.checkout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "boutique.fullname" . }}-checkout
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "boutique.checkoutSelectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.checkout.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "boutique.checkoutSelectorLabels" . | nindent 4 }}
{{- end }}
